### ISSUE TITLE
Edit option on project request broken 

### ISSUE THREAD

**Issue by MrPrecise** [AutoPacker-OSS/AutoPacker#184] opened 2021-04-08 13:58 UTC
Description
-

Attempting to edit a project request will yield an error

[![Image from Gyazo](https://i.gyazo.com/ce99fe12f4d5e419063deeca43414bcf.gif)](https://gyazo.com/ce99fe12f4d5e419063deeca43414bcf)

**Comment by ANicholasson** [comment] 2021-04-08 14:04
Duplicate of #180

**Closed as completed** 2021-04-08 18:01 UTC
Labels: Type: Bug, Priority: Critical, Service: Web App
