### ISSUE TITLE
ERROR: Failed to connect to localhost port 8090: Connection Refused

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#29] opened 2020-10-01 15:58 UTC
Gets this error when trying to fetch the docker-compose from file delivery api when trying to deploy a project to a server

**Comment by libanbn** [comment] 2021-01-18 16:25
Might be something related to configuration. Assuming the APIs are running on the same server, are you sure file delivery API is running?

Going to close this issue for now, but can later be reopened if the issue is preset across all instances of the API(s).

**Closed by libanbn** 2021-01-18 16:25 UTC
Labels: Status: Revision Needed, bug
